### PR TITLE
glob resolver looks for files in modules

### LINKED ISSUE #15: Cannot get glob modules to work
A very simple testcase is `@import asm.css/lib/align-self/*.css;` where asm.css is a node_module, it seems easy import isn't resolving it for some reason?

Relevant files

postcss.config.js (using postcss-cli)
````
module.exports = (ctx) => ({
  'no-map': true,
  plugins: {
    'postcss-easy-import': {},
    'postcss-reporter': {}
  }
})
````

building:
`./node_modules/.bin/postcss $file -o $ofile`
where $file is
`@import "asm.css/lib/align-self/*.css";`
of which asm.css/lib/align-self/* exists and has files in node_modules

### PR DESCRIPTION
**Pull request by marzelin**
For non-relative globs, glob resolver looks for files also in `node_modules` and `web_modules`

Closes #15

### CODE REVIEW

**Comment by simonsmith** [comment]
Thanks for this @marzelin.

What do you think about adding a unit test for this too?

**Comment by marzelin** [comment]
@simonsmith is there a way to test this behavior without pulling down some css library?

**Comment by simonsmith** [comment]
Yeah, if you test the `resolveGlob` function directly you can avoid all the `postcss` plugin stuff. Some of the existing tests should give you an idea - https://github.com/marzelin/postcss-easy-import/blob/7de8b90c0b6d5274653a0aa8a08320b83a5ba178/test/resolve-glob.js

Does that help?

**Comment by TrySound** [comment]
@marzelin You may just add node_modules dir in test fixtures

**Comment by marzelin** [comment]
Tests added, but they will break if you upgrade ava since they changed how the current working directory in test files is calculated.

**Comment by simonsmith** [comment]
Yeah, I had trouble upgrading `ava` before so I've left it for now. This looks good to me. @TrySound?

**Comment by TrySound** [comment]
Yep. lgtm
I like jest now, if you don't want to use ava.

**Comment by simonsmith** [comment]
> I like jest now, if you don't want to use ava

Same! Perhaps that can be a separate chore task

@marzelin Thanks very much for this! Merging.

**Comment by simonsmith** [comment]
Released in `2.1.0`

**Pull request merged**
