### PR TITLE
Dynamic resolve option (module + globbing)

### PR DESCRIPTION
**Pull request by toomuchdesign**
Set up a dynamic resolve option to dynamically switch between globbing and module imports.

**What's new**
I created a new `resolveDynamic` resolver which requires `is-glob` package and both the original resolvers packed with this plugin. When `resolveDynamic` is enabled, each @import url is tested against `is-glob` regex and then processed by one of the original resolvers according to `is-glob`result.

**resolveDynamic option**
Added a new `resolveDynamic` option (`false` by default), which enables dynamic resolve only when set to `true` and when `glob` option is `false`.

**Option name**
`dynamicResolve` or `resolveDynamically` might be a better name for the new option ;-).

### CODE REVIEW

**Comment by timkelty** [comment]
Eagerly awaiting a resolution to #6. This was functionality `postcss-import` 7.x had before it removed globbing, so I'm relying on it.

**Comment by gunzip** [comment]
same here, please merge :)

**Comment by snuggs** [comment]
@TrySound #ping? 🚢  :shipit: /cc @toomuchdesign @timkelty @gunzip

**Comment by simonsmith** [comment]
@TrySound kindly made me a collaborator so we can get some outstanding issues resolved. I'll take a look at this PR later on as it seems like a great addition :)

**Comment by snuggs** [comment]
Nice @simonsmith. Hope the 👊  bump helped. ;-) Love this project and glad to see you aboard! Gotta keep momentum going. 🙏  What left do we have to do to merge this in?

**Comment by simonsmith** [comment]
I'm currently just working on upgrading some of the dependencies. Moving to latest AVA broke all the tests bizarrely. Once that is sorted I can address the changes here

**Comment by toomuchdesign** [comment]
Hi @simonsmith, you probably know, but AVA 0.17.0 changes `process.cwd()` behaviour. Already hit that once!
https://github.com/avajs/ava/releases/tag/v0.17.0

**Comment by simonsmith** [comment]
@toomuchdesign Oh nice, that might be my exact issue as all the tests were failing to resolve modules. I haven't used AVA before so wasn't up to date on changes. Thanks for the tip!

**Comment by simonsmith** [comment]
I was also wondering about whether this feature should be a default rather than behind an option. We could remove `glob` as an option and just let the plugin decide what to do based on `isGlob`.

So something like this in `index.js`:

``` js
opts.resolve = function(id, base, opts) {
    if (isGlob(id)) {
        return resolveGlob(id, base, opts);
    } 
    return resolveModule(id, base, opts);
};
```

I can't see a reason why someone would pick glob or resolve if it could be done dynamically.

**Comment by toomuchdesign** [comment]
Probably someone might want to be able to preventively select just `glob` or `module` resolve in order to be sure that nothing is imported by chance. But it's just speculation! Thanks for handling the maintainance , @simonsmith.

Cheers!

**Comment by simonsmith** [comment]
True, although if you're using globs you would probably know what to expect. For example not caring about order of imports.

My thoughts were that this should work out of the box:

```js
@import "suitcss-base";
@import "./components/*.css";
```

Are you happy to rebase this with master and/or make changes @toomuchdesign? I can understand if not as it's months old. If not I'll pull your branch and make the updates.

**Comment by toomuchdesign** [comment]
Ok! I'll try to push something before next Monday.

**Comment by simonsmith** [comment]
Closing in favour of #13

**Comment by simonsmith** [comment]
Fixed in https://github.com/TrySound/postcss-easy-import/pull/14

**Pull request closed without merging**
